// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByVsfOLON7NHCKq79I4NdnIHs8iRC-rww',
    appId: '1:63446976849:web:935b55867e1a30fc282b70',
    messagingSenderId: '63446976849',
    projectId: 'diary-system',
    authDomain: 'diary-system.firebaseapp.com',
    storageBucket: 'diary-system.firebasestorage.app',
    measurementId: 'G-LYE0G713RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKJrfMls60dWHnDgdTx_WvFDijdR7kN3s',
    appId: '1:63446976849:android:7dd53851d078302c282b70',
    messagingSenderId: '63446976849',
    projectId: 'diary-system',
    storageBucket: 'diary-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqG4fzUMksoi3v9g2K5RQVIht1689xqdU',
    appId: '1:63446976849:ios:ffdb74da55e73d55282b70',
    messagingSenderId: '63446976849',
    projectId: 'diary-system',
    storageBucket: 'diary-system.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );
}
